### ISSUE TITLE
Connection via Proxy

### ISSUE THREAD

**Issue by ricktg** [DataDog/logstash-output-datadog_logs#4]
**Describe what happened:**
This plugin does not seem to inherit logstash proxy configuration.

**Describe what you expected:**
Use logstash proxy config

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by NBParis** [comment]
Hello @ricktg,

First of all, thanks for reaching and helping us improve this plugin.
Would it be possible to have more details about the setup you have for your proxy?

To give some context about my question, this plugin forward logs with a TLS-encrypted connection to Datadog intake. 
So in order to be able to send logs to the proxy, we would need to remove the TLS-encryption as your proxy will not be able to validate our certificate, and probably to change the endpoint as well.

Thanks

**Comment by ricktg** [comment]
Hi @NBParis,

Our current logstash setup has the java system property http.proxyHost and http.proxyPort configured in the startup script. 
So the suggestion would be the plugin use this properties as proxy configuration.

Out datadog agent already has proxy configured as well to send the standard monitoring metrics.

Let me know if you need more info.

**Comment by NBParis** [comment]
@ricktg So the main difference here is that the Datadog Logstash plugin is using TCP to forward logs and not HTTP which is probably one of the reason those parameters are not taken into account.

Something we could look into is to:

1.  let you define a proxy endpoint (host and port) in the plugin
2.  add an option to disable TLS encryption between Logstash and the proxy (as your proxy won't be able to validate our certificate)

What are your thoughts on this?

**Comment by ricktg** [comment]
@NBParis, to should work perfectly in my case! I would even be able to remove the proxy system property since i've put there just for testing the datadog connection.

Thanks for the help!

**Comment by ajacquemot** [comment]
Hi @ricktg,

We've just released a new version of the plugin containing the proxy settings logic, happy testing.
Thanks,

Alexandre
